name: release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  TOOLCHAIN: nightly

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Cargo cache
      - name: Cargo cache
        id: cache-cargo
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin
          key: cargo

      # Install cargo deps
      - name: Pull Cargo dependencies
        if: steps.cache-cargo.outputs.cache-hit != 'true'
        run: |
          rustup update $TOOLCHAIN
          rustup default $TOOLCHAIN
          cargo install trunk
          rustup target add wasm32-unknown-unknown

      # Pull website
      - name: Build cache
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ./dist
          key: release-${{ hashFiles('./src') }}-${{ hashFiles('./index.html') }}

      # Install cargo deps
      - name: Trunk build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          npm install tailwindcss --global
          trunk build --release --public-url /excalidraw-wasm/

      # Deploy, GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist